global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '127.0.0.1:9090' ]

  - job_name: 'user-rpc'
    static_configs:
      - targets: [ '172.17.0.1:9061' ]

  - job_name: 'pair-rpc'
    static_configs:
      - targets: [ '172.17.0.1:9062' ]

  - job_name: 'chat-rpc'
    static_configs:
      - targets: [ '172.17.0.1:9063' ]

  - job_name: 'user-api'
    static_configs:
      - targets: [ '172.17.0.1:9051' ]

  - job_name: 'pair-api'
    static_configs:
      - targets: [ '172.17.0.1:9052' ]

  - job_name: 'chat-api'
    static_configs:
      - targets: [ '172.17.0.1:9053' ]