apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rpc
  namespace: acger
  labels:
    app: user-rpc
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: user-rpc
  template:
    metadata:
      labels:
        app: user-rpc
    spec:
      containers:
        - name: user-rpc
          image: docker.io/dk251626910/ffl-user-rpc:latest
          lifecycle:
            preStop:
              exec:
                command: [ "sh","-c","sleep 5" ]
          ports:
            - containerPort: 60001
            - containerPort: 9061
          readinessProbe:
            tcpSocket:
              port: 60001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 60001
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            - name: log
              mountPath: /var/log/acger-pair/user-rpc
            - name: config
              mountPath: /app/etc
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: log
          hostPath:
            path: /var/log/acger-pair/user-rpc
        - name: config
          configMap:
            name: acger-config
            items:
              - key: user-rpc.yaml
                path: user.yaml
---

apiVersion: v1
kind: Service
metadata:
  name: user-rpc-svc
  namespace: acger
spec:
  ports:
    - name: main
      port: 60001
    - name: metrics
      port: 9061
  selector:
    app: user-rpc
