// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	ele "pair/service/pair/api/internal/handler/ele"
	"pair/service/pair/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/pair/element/save",
				Handler: ele.SaveElementHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pair/element",
				Handler: ele.ElementHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pair/element/list",
				Handler: ele.ListElementHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pair/element/pair",
				Handler: pairHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
