// Code generated by goctl. DO NOT EDIT!
// Source: chat.proto

package server

import (
	"context"

	"pair/service/chat/rpc/chat/pb"
	"pair/service/chat/rpc/internal/logic"
	"pair/service/chat/rpc/internal/svc"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) MessageSave(ctx context.Context, in *pb.MsgSaveReq) (*pb.Rsp, error) {
	l := logic.NewMessageSaveLogic(ctx, s.svcCtx)
	return l.MessageSave(in)
}

func (s *ChatServer) MessageList(ctx context.Context, in *pb.MsgListReq) (*pb.MsgListRsp, error) {
	l := logic.NewMessageListLogic(ctx, s.svcCtx)
	return l.MessageList(in)
}

func (s *ChatServer) ChatHistoryList(ctx context.Context, in *pb.ChatHistoryReq) (*pb.ChatHistoryRsp, error) {
	l := logic.NewChatHistoryListLogic(ctx, s.svcCtx)
	return l.ChatHistoryList(in)
}

func (s *ChatServer) ChatNumber(ctx context.Context, in *pb.ChatNumberReq) (*pb.ChatNumberRsp, error) {
	l := logic.NewChatNumberLogic(ctx, s.svcCtx)
	return l.ChatNumber(in)
}

func (s *ChatServer) ChatHistorySave(ctx context.Context, in *pb.CHSaveReq) (*pb.Rsp, error) {
	l := logic.NewChatHistorySaveLogic(ctx, s.svcCtx)
	return l.ChatHistorySave(in)
}
