// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgSaveReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ToUid                int64    `protobuf:"varint,2,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Status               bool     `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSaveReq) Reset()         { *m = MsgSaveReq{} }
func (m *MsgSaveReq) String() string { return proto.CompactTextString(m) }
func (*MsgSaveReq) ProtoMessage()    {}
func (*MsgSaveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *MsgSaveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSaveReq.Unmarshal(m, b)
}
func (m *MsgSaveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSaveReq.Marshal(b, m, deterministic)
}
func (m *MsgSaveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSaveReq.Merge(m, src)
}
func (m *MsgSaveReq) XXX_Size() int {
	return xxx_messageInfo_MsgSaveReq.Size(m)
}
func (m *MsgSaveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSaveReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSaveReq proto.InternalMessageInfo

func (m *MsgSaveReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MsgSaveReq) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *MsgSaveReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MsgSaveReq) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Rsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rsp) Reset()         { *m = Rsp{} }
func (m *Rsp) String() string { return proto.CompactTextString(m) }
func (*Rsp) ProtoMessage()    {}
func (*Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rsp.Unmarshal(m, b)
}
func (m *Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rsp.Marshal(b, m, deterministic)
}
func (m *Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rsp.Merge(m, src)
}
func (m *Rsp) XXX_Size() int {
	return xxx_messageInfo_Rsp.Size(m)
}
func (m *Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_Rsp proto.InternalMessageInfo

func (m *Rsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Rsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MsgListReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ToUid                int64    `protobuf:"varint,2,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize             int64    `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgListReq) Reset()         { *m = MsgListReq{} }
func (m *MsgListReq) String() string { return proto.CompactTextString(m) }
func (*MsgListReq) ProtoMessage()    {}
func (*MsgListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *MsgListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgListReq.Unmarshal(m, b)
}
func (m *MsgListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgListReq.Marshal(b, m, deterministic)
}
func (m *MsgListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgListReq.Merge(m, src)
}
func (m *MsgListReq) XXX_Size() int {
	return xxx_messageInfo_MsgListReq.Size(m)
}
func (m *MsgListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgListReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgListReq proto.InternalMessageInfo

func (m *MsgListReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MsgListReq) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *MsgListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *MsgListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ChatMessage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ToUid                int64    `protobuf:"varint,3,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Status               bool     `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChatMessage) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ChatMessage) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatMessage) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type MsgListRsp struct {
	Msg                  []*ChatMessage `protobuf:"bytes,1,rep,name=Msg,proto3" json:"Msg,omitempty"`
	Total                int64          `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Page                 int64          `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize             int64          `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	Code                 int64          `protobuf:"varint,5,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string         `protobuf:"bytes,6,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MsgListRsp) Reset()         { *m = MsgListRsp{} }
func (m *MsgListRsp) String() string { return proto.CompactTextString(m) }
func (*MsgListRsp) ProtoMessage()    {}
func (*MsgListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *MsgListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgListRsp.Unmarshal(m, b)
}
func (m *MsgListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgListRsp.Marshal(b, m, deterministic)
}
func (m *MsgListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgListRsp.Merge(m, src)
}
func (m *MsgListRsp) XXX_Size() int {
	return xxx_messageInfo_MsgListRsp.Size(m)
}
func (m *MsgListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgListRsp proto.InternalMessageInfo

func (m *MsgListRsp) GetMsg() []*ChatMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *MsgListRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MsgListRsp) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *MsgListRsp) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *MsgListRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MsgListRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChatHistoryReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatHistoryReq) Reset()         { *m = ChatHistoryReq{} }
func (m *ChatHistoryReq) String() string { return proto.CompactTextString(m) }
func (*ChatHistoryReq) ProtoMessage()    {}
func (*ChatHistoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *ChatHistoryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatHistoryReq.Unmarshal(m, b)
}
func (m *ChatHistoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatHistoryReq.Marshal(b, m, deterministic)
}
func (m *ChatHistoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatHistoryReq.Merge(m, src)
}
func (m *ChatHistoryReq) XXX_Size() int {
	return xxx_messageInfo_ChatHistoryReq.Size(m)
}
func (m *ChatHistoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatHistoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatHistoryReq proto.InternalMessageInfo

func (m *ChatHistoryReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ChatUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=Account,proto3" json:"Account,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Status               bool     `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatUser) Reset()         { *m = ChatUser{} }
func (m *ChatUser) String() string { return proto.CompactTextString(m) }
func (*ChatUser) ProtoMessage()    {}
func (*ChatUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *ChatUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatUser.Unmarshal(m, b)
}
func (m *ChatUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatUser.Marshal(b, m, deterministic)
}
func (m *ChatUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatUser.Merge(m, src)
}
func (m *ChatUser) XXX_Size() int {
	return xxx_messageInfo_ChatUser.Size(m)
}
func (m *ChatUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatUser.DiscardUnknown(m)
}

var xxx_messageInfo_ChatUser proto.InternalMessageInfo

func (m *ChatUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChatUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatUser) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ChatUser) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ChatUser) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ChatHistoryRsp struct {
	Code                 int64       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	User                 []*ChatUser `protobuf:"bytes,3,rep,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChatHistoryRsp) Reset()         { *m = ChatHistoryRsp{} }
func (m *ChatHistoryRsp) String() string { return proto.CompactTextString(m) }
func (*ChatHistoryRsp) ProtoMessage()    {}
func (*ChatHistoryRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *ChatHistoryRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatHistoryRsp.Unmarshal(m, b)
}
func (m *ChatHistoryRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatHistoryRsp.Marshal(b, m, deterministic)
}
func (m *ChatHistoryRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatHistoryRsp.Merge(m, src)
}
func (m *ChatHistoryRsp) XXX_Size() int {
	return xxx_messageInfo_ChatHistoryRsp.Size(m)
}
func (m *ChatHistoryRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatHistoryRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatHistoryRsp proto.InternalMessageInfo

func (m *ChatHistoryRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ChatHistoryRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatHistoryRsp) GetUser() []*ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

type ChatNumberReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatNumberReq) Reset()         { *m = ChatNumberReq{} }
func (m *ChatNumberReq) String() string { return proto.CompactTextString(m) }
func (*ChatNumberReq) ProtoMessage()    {}
func (*ChatNumberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{8}
}

func (m *ChatNumberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatNumberReq.Unmarshal(m, b)
}
func (m *ChatNumberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatNumberReq.Marshal(b, m, deterministic)
}
func (m *ChatNumberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatNumberReq.Merge(m, src)
}
func (m *ChatNumberReq) XXX_Size() int {
	return xxx_messageInfo_ChatNumberReq.Size(m)
}
func (m *ChatNumberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatNumberReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatNumberReq proto.InternalMessageInfo

func (m *ChatNumberReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ChatNumberRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Number               int64    `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatNumberRsp) Reset()         { *m = ChatNumberRsp{} }
func (m *ChatNumberRsp) String() string { return proto.CompactTextString(m) }
func (*ChatNumberRsp) ProtoMessage()    {}
func (*ChatNumberRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{9}
}

func (m *ChatNumberRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatNumberRsp.Unmarshal(m, b)
}
func (m *ChatNumberRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatNumberRsp.Marshal(b, m, deterministic)
}
func (m *ChatNumberRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatNumberRsp.Merge(m, src)
}
func (m *ChatNumberRsp) XXX_Size() int {
	return xxx_messageInfo_ChatNumberRsp.Size(m)
}
func (m *ChatNumberRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatNumberRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatNumberRsp proto.InternalMessageInfo

func (m *ChatNumberRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ChatNumberRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatNumberRsp) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CHSaveReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ToUid                int64    `protobuf:"varint,2,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CHSaveReq) Reset()         { *m = CHSaveReq{} }
func (m *CHSaveReq) String() string { return proto.CompactTextString(m) }
func (*CHSaveReq) ProtoMessage()    {}
func (*CHSaveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{10}
}

func (m *CHSaveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CHSaveReq.Unmarshal(m, b)
}
func (m *CHSaveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CHSaveReq.Marshal(b, m, deterministic)
}
func (m *CHSaveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CHSaveReq.Merge(m, src)
}
func (m *CHSaveReq) XXX_Size() int {
	return xxx_messageInfo_CHSaveReq.Size(m)
}
func (m *CHSaveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CHSaveReq.DiscardUnknown(m)
}

var xxx_messageInfo_CHSaveReq proto.InternalMessageInfo

func (m *CHSaveReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CHSaveReq) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgSaveReq)(nil), "chat.MsgSaveReq")
	proto.RegisterType((*Rsp)(nil), "chat.Rsp")
	proto.RegisterType((*MsgListReq)(nil), "chat.MsgListReq")
	proto.RegisterType((*ChatMessage)(nil), "chat.ChatMessage")
	proto.RegisterType((*MsgListRsp)(nil), "chat.MsgListRsp")
	proto.RegisterType((*ChatHistoryReq)(nil), "chat.ChatHistoryReq")
	proto.RegisterType((*ChatUser)(nil), "chat.ChatUser")
	proto.RegisterType((*ChatHistoryRsp)(nil), "chat.ChatHistoryRsp")
	proto.RegisterType((*ChatNumberReq)(nil), "chat.ChatNumberReq")
	proto.RegisterType((*ChatNumberRsp)(nil), "chat.ChatNumberRsp")
	proto.RegisterType((*CHSaveReq)(nil), "chat.CHSaveReq")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0x96, 0xbd, 0x86, 0xc2, 0xa0, 0x92, 0x74, 0x1a, 0x45, 0x96, 0x2f, 0xb5, 0xdc, 0x0b, 0xaa,
	0x54, 0xa2, 0x06, 0xa9, 0xb7, 0x1e, 0x52, 0x2e, 0x44, 0x2a, 0x51, 0xb5, 0x94, 0x4b, 0x6f, 0x0b,
	0x6c, 0x09, 0x52, 0x52, 0xbb, 0xde, 0x25, 0xfd, 0x79, 0x85, 0x3e, 0x47, 0xdf, 0xb3, 0x9a, 0xf5,
	0x9a, 0xc5, 0x60, 0x0e, 0x3e, 0x31, 0x33, 0x9e, 0xdd, 0xef, 0x67, 0x66, 0x01, 0x58, 0xde, 0x0b,
	0x3d, 0xcc, 0xf2, 0x54, 0xa7, 0x18, 0x50, 0x9c, 0x7c, 0x03, 0x98, 0xaa, 0xf5, 0x4c, 0x3c, 0x49,
	0x2e, 0x7f, 0xe0, 0x39, 0xb0, 0xf9, 0x66, 0x15, 0x7a, 0xb1, 0x37, 0x60, 0x9c, 0x42, 0xbc, 0x80,
	0xd6, 0x97, 0x94, 0x6a, 0xbe, 0xa9, 0x15, 0x09, 0x86, 0xf0, 0x6c, 0x2a, 0x95, 0x12, 0x6b, 0x19,
	0xb2, 0xd8, 0x1b, 0x74, 0x79, 0x99, 0xe2, 0x25, 0xb4, 0x67, 0x5a, 0xe8, 0xad, 0x0a, 0x83, 0xd8,
	0x1b, 0x74, 0xb8, 0xcd, 0x92, 0x11, 0x30, 0xae, 0x32, 0x44, 0x08, 0xc6, 0xe9, 0x4a, 0x5a, 0x04,
	0x13, 0xef, 0x5f, 0xe6, 0x57, 0x2e, 0x4b, 0x56, 0x86, 0xdc, 0xa7, 0x8d, 0xd2, 0x4d, 0xc8, 0x21,
	0x04, 0x9f, 0x4b, 0x66, 0x8c, 0x9b, 0x18, 0x23, 0xe8, 0xd0, 0xef, 0x6c, 0xf3, 0x47, 0x1a, 0x62,
	0x8c, 0xef, 0xf2, 0xe4, 0x27, 0xf4, 0xc6, 0xf7, 0x42, 0x97, 0x0a, 0xfa, 0xe0, 0xdf, 0x96, 0x28,
	0xfe, 0xed, 0xaa, 0x84, 0xf5, 0x6b, 0x60, 0xd9, 0x09, 0x4f, 0x82, 0x53, 0x9e, 0xb4, 0x2a, 0x9e,
	0xfc, 0xf3, 0x9c, 0x3e, 0x95, 0xe1, 0x6b, 0x60, 0x53, 0xb5, 0x0e, 0xbd, 0x98, 0x0d, 0x7a, 0xd7,
	0x2f, 0x86, 0x66, 0x54, 0x7b, 0xc4, 0x38, 0x7d, 0x2d, 0xb0, 0xb5, 0x78, 0x70, 0x92, 0xb5, 0x78,
	0x68, 0x2a, 0x79, 0x37, 0x86, 0x56, 0xfd, 0x18, 0xda, 0xd5, 0x31, 0xc4, 0xd0, 0x27, 0x1e, 0x93,
	0x8d, 0xd2, 0x69, 0xfe, 0x9b, 0x46, 0x71, 0xe0, 0x51, 0xf2, 0x0b, 0x3a, 0xd4, 0x31, 0x57, 0x32,
	0x3f, 0xf2, 0x0f, 0x21, 0xb8, 0x13, 0x8f, 0xe5, 0x6c, 0x4d, 0x4c, 0x58, 0x37, 0xcb, 0x65, 0xba,
	0xfd, 0xae, 0xcb, 0xfd, 0xb1, 0x29, 0x79, 0x75, 0xf3, 0x24, 0xb4, 0xc8, 0xad, 0x89, 0x36, 0x3b,
	0xe9, 0xe1, 0xa2, 0xca, 0xad, 0xe9, 0x8a, 0x61, 0x02, 0x01, 0xb1, 0x0e, 0x99, 0x71, 0xbd, 0xef,
	0x5c, 0xa7, 0x2a, 0x37, 0xdf, 0x92, 0x57, 0xf0, 0x9c, 0x2a, 0x77, 0xdb, 0xc7, 0x85, 0xcc, 0xeb,
	0xe4, 0xcf, 0x2b, 0x0d, 0x8d, 0x39, 0x5c, 0x42, 0xbb, 0x38, 0x6a, 0xe7, 0x67, 0xb3, 0x64, 0x04,
	0xdd, 0xf1, 0xa4, 0xe1, 0xd3, 0xbc, 0xfe, 0xeb, 0x43, 0x40, 0x64, 0xf0, 0x0d, 0xf4, 0x2c, 0x00,
	0x5d, 0x81, 0xe7, 0x85, 0x34, 0xf7, 0xd8, 0xa3, 0x6e, 0x51, 0x21, 0xbe, 0xef, 0x76, 0xbd, 0xb4,
	0x8c, 0x7b, 0xbd, 0xf6, 0xed, 0x45, 0x07, 0x15, 0x95, 0xe1, 0x07, 0x38, 0xdb, 0x33, 0xde, 0x1c,
	0xbb, 0x70, 0xee, 0xb9, 0x5d, 0x89, 0x6a, 0xaa, 0x2a, 0xc3, 0xf7, 0x00, 0xce, 0x32, 0x7c, 0xe9,
	0x7a, 0x76, 0x2e, 0x47, 0xc7, 0x45, 0x95, 0xe1, 0xdb, 0x0a, 0xac, 0x51, 0x76, 0x66, 0xfb, 0x26,
	0xc7, 0xc2, 0x3e, 0xf6, 0xbe, 0x76, 0x87, 0x57, 0x94, 0x5d, 0x65, 0x8b, 0x45, 0xdb, 0xfc, 0xf1,
	0x8d, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x57, 0x10, 0x60, 0x06, 0x05, 0x00, 0x00,
}
