// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id      string `json:"id"`
	Account string `json:"account"`
	Name    string `json:"name,optional"`
	Avatar  string `json:"avatar,optional"`
}

type RegisterReq struct {
	Account  string `json:"account" validate:"required,alphanum,min=6,max=30"`
	Password string `json:"password" validate:"required,min=6,max=30"`
	Name     string `json:"name,optional" validate:"max=30"`
	Avatar   string `json:"avatar,optional"`
}

type RegisterRsp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	User    User   `json:"user"`
	Token   string `json:"token"`
}

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginRsp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	User    User   `json:"user"`
	Token   string `json:"token"`
}

type ProfileRsp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	User    User   `json:"user"`
}

type EditReq struct {
	Name     string `json:"name,optional" validate:"max=30"`
	Avatar   string `json:"avatar,optional"`
	Password string `json:"password,optional" validate:"required,min=6,max=30"`
}

type EditRsp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type QiniuUpReq struct {
	Name string `json:"name"`
}

type QiniuUpRsp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Token   string `json:"token"`
}

type Rsp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}
