name: pair-api

on:
  push:
    branches: [ main ]
    paths:
      - service/pair/api/**
jobs:
  build:
    name: deploy-pair-api
    runs-on: ubuntu-latest
    environment: pro
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=UTC-8 date +'%Y%m%d-%H%M%S')"

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          file:
            deploy/actions/dockerfile/pair-api
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ffl-pair-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ffl-pair-api:${{ steps.date.outputs.date }}

      - name: kubectl-simple
        uses: steebchen/kubectl@v2.0.0
        with:
          config:
            ${{ secrets.KUBECTL_CONFIG }}
          command:
            set image deployment/pair-api pair-api=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ffl-pair-api:${{ steps.date.outputs.date }} -n acger